<a href="https://colab.research.google.com/github/Charly156/Actividad_1/blob/main/1_3_Inmuebles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos librerias requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Se lee el archivo excel sin índice
df = pd.read_excel('Inmuebles.xlsx', skiprows=1)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3337 entries, 0 to 3336
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Referencia    3337 non-null   int64
 1   Fecha_Alta    3337 non-null   datetime64[ns]
 2   Tipo          3337 non-null   object
 3   Operación     3337 non-null   object
 4   Provincia     3337 non-null   object
 5   Superficie    3335 non-null   float64
 6   Precio Venta  3335 non-null   float64
 7   Fecha Venta   2759 non-null   datetime64[ns]
 8   Vendedor      2759 non-null   object
dtypes: datetime64[ns](2), float64(2), int64(1), object(4)
memory usage: 234.8+ KB

In [4]:
filtro1 = df.iloc[:,1:8]
filtro1

,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta
0,2004-01-01,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19
1,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19
2,2004-01-01,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08
3,2004-01-02,Parking,Alquiler,Girona,285.0,NaN,2004-04-27
4,2004-01-02,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10
...,...,...,...,...,...,...,...
3332,2007-04-29,Industrial,Alquiler,Lleida,221.0,1450644.0,NaT
3333,2007-04-29,Piso,Alquiler,Girona,55.0,454080.0,NaT
3334,2007-04-30,Suelo,Venta,Tarragona,78.0,740688.0,NaT
3335,2007-04-30,Piso,Alquiler,Barcelona,88.0,397408.0,NaT
3336,2007-04-30,Parking,Venta,Lleida,254.0,2140712.0,NaT

In [5]:
filtro4 =  df[(df['Provincia'] == 'Girona') & (df['Superficie'] > 100)]
filtro4

,Referencia,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
1,2,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
3,4,2004-01-02,Parking,Alquiler,Girona,285.0,NaN,2004-04-27,Jesús
5,6,2004-01-03,Industrial,Alquiler,Girona,131.0,953156.0,2004-09-05,Pedro
7,8,2004-01-03,Oficina,Venta,Girona,235.0,2158475.0,2004-10-31,Jesús
10,11,2004-01-04,Oficina,Alquiler,Girona,124.0,627068.0,2004-10-28,Pedro
...,...,...,...,...,...,...,...,...,...
3299,3300,2007-04-12,Local,Alquiler,Girona,156.0,881868.0,NaT,NaN
3303,3304,2007-04-12,Piso,Venta,Girona,128.0,1270400.0,NaT,NaN
3306,3307,2007-04-14,Parking,Venta,Girona,221.0,1533077.0,NaT,NaN
3316,3317,2007-04-20,Casa,Venta,Girona,247.0,1804088.0,NaT,NaN
3330,3331,2007-04-27,Local,Venta,Girona,110.0,845790.0,NaT,NaN

In [6]:
filtro5 = df[(df['Precio Venta'] > 1000000) | (df['Vendedor'] == 'Cameron') | (df['Vendedor'] == 'Joaquín')]
filtro5

,Referencia,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,1,2004-01-01,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19,Carmen
1,2,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
2,3,2004-01-01,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08,Joaquín
7,8,2004-01-03,Oficina,Venta,Girona,235.0,2158475.0,2004-10-31,Jesús
8,9,2004-01-04,Piso,Alquiler,Lleida,108.0,1024380.0,2004-12-28,Jesús
...,...,...,...,...,...,...,...,...,...
3325,3326,2007-04-25,Industrial,Alquiler,Barcelona,296.0,2078216.0,NaT,NaN
3328,3329,2007-04-26,Piso,Venta,Barcelona,264.0,2517504.0,NaT,NaN
3331,3332,2007-04-29,Oficina,Venta,Lleida,190.0,1031320.0,NaT,NaN
3332,3333,2007-04-29,Industrial,Alquiler,Lleida,221.0,1450644.0,NaT,NaN
3336,3337,2007-04-30,Parking,Venta,Lleida,254.0,2140712.0,NaT,NaN

In [7]:
filtro6 = df[~(df['Provincia'] == 'Barcelona')]
filtro6

,Referencia,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,1,2004-01-01,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19,Carmen
1,2,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
2,3,2004-01-01,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08,Joaquín
3,4,2004-01-02,Parking,Alquiler,Girona,285.0,NaN,2004-04-27,Jesús
4,5,2004-01-02,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10,María
...,...,...,...,...,...,...,...,...,...
3331,3332,2007-04-29,Oficina,Venta,Lleida,190.0,1031320.0,NaT,NaN
3332,3333,2007-04-29,Industrial,Alquiler,Lleida,221.0,1450644.0,NaT,NaN
3333,3334,2007-04-29,Piso,Alquiler,Girona,55.0,454080.0,NaT,NaN
3334,3335,2007-04-30,Suelo,Venta,Tarragona,78.0,740688.0,NaT,NaN
3336,3337,2007-04-30,Parking,Venta,Lleida,254.0,2140712.0,NaT,NaN

In [8]:
filtro7 = df[~(df['Operación'] == 'Alquiler') & ~(df['Tipo'] == 'Oficina')]
filtro7

,Referencia,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
1,2,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
4,5,2004-01-02,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10,María
9,10,2004-01-04,Parking,Venta,Lleida,299.0,2042768.0,2004-10-06,Joaquín
11,12,2004-01-04,Industrial,Venta,Girona,187.0,999328.0,2004-04-05,Carmen
12,13,2004-01-04,Parking,Venta,Barcelona,NaN,2937300.0,2004-11-04,Jesús
...,...,...,...,...,...,...,...,...,...
3328,3329,2007-04-26,Piso,Venta,Barcelona,264.0,2517504.0,NaT,NaN
3329,3330,2007-04-27,Parking,Venta,Barcelona,88.0,612568.0,NaT,NaN
3330,3331,2007-04-27,Local,Venta,Girona,110.0,845790.0,NaT,NaN
3334,3335,2007-04-30,Suelo,Venta,Tarragona,78.0,740688.0,NaT,NaN
3336,3337,2007-04-30,Parking,Venta,Lleida,254.0,2140712.0,NaT,NaN

In [9]:
filtro1.to_csv('1.3 Filtro1.csv')
filtro4.to_csv('1.3 Filtro4.csv')
filtro5.to_csv('1.3 Filtro5.csv')
filtro6.to_csv('1.3 Filtro6.csv')
filtro7.to_csv('1.3 Filtro7.csv')